settings = {
    'workload':
    [
        {'site':'https://essaysparlour.com/',
         'posts':5,
         'category':'physics',
         'year':2017
        },
        {'site':'https://essaysparlour.com/thesishelp/',
         'posts':5,
         'category':'economics',
         'year':2017
        },
        {'site':'https://essaysparlour.com/science-papers/',
         'posts':5,
         'category':'physics',
         'year':2017
        },
        {'site':'https://essaysparlour.com/term-papers/',
         'posts':5,
         'category':'nursing',
         'year':2017
        },
        {'site':'https://essaysparlour.com/physics-solutions/',
         'posts':5,
         'category':'physics',
         'year':2017
        },
        {'site':'https://academichelp.essaysparlour.com/',
         'posts':30,
         'category':'finance',
         'year':2017
        },
        {'site':'https://academichelp.essayparlour.com/',
         'posts':30,
         'category':'physics',
         'year':2017
        },
        {'site':'https://hireessaywriters.com/statistics-probability/',
         'posts':30,
         'category':'economics',
         'year':2017
        },
        {'site':'https://hireessaywriters.com/brilliant-solutions/',
         'posts':30,
         'category':'finance',
         'year':2017
        },
        {'site':'https://hireessaywriters.com/essaysolutions/',
         'posts':30,
         'category':'nursing',
         'year':2017
        },
        {'site':'https://hireessaywriters.com/homeworkhelp/',
         'posts':20,
         'category':'economics',
         'year':2017
        },
        {'site':'https://hireessaywriters.com/assignment-help/',
         'posts':20,
         'category':'finance',
         'year':2017
        },
        {'site':'https://essays.hireessaywriters.com/',
         'posts':20,
         'category':'finance',
         'year':2017
        },
        {'site':'https://termpapers.hireessaywriters.com/',
         'posts':20,
         'category':'finance',
         'year':2017
        },
    ]
}
